name: tqftpserv
on:
  push:
    branches: [main, sdm845-odin]
    paths: ['tqftpserv/**', 'oci/**', 'scripts/**', 'toolchain.env', '.forgejo/workflows/tqftpserv.yml', '.forgejo/workflows/_package-image.yml']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    uses: ./.forgejo/workflows/_package-image.yml
    secrets: inherit
    with:
      package: tqftpserv
